name: oit_portal_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.4+5
  url_launcher: ^5.2.5
  flutter_webview_plugin: ^0.3.8
  html: ^0.14.0+3
  http: ^0.12.0+2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
